[package]
name = "os_school"
version = "0.1.0"
edition = "2021"
description = "A test package just for my Operating System Subject"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
[profile.release]
panic = 'abort'